### ISSUE TITLE
Request for Code Acknowledgment and License Clarification

### ISSUE THREAD

**Issue by ABaldrati** [navervision/lincir#1]
Hi there!

First of all, I've been reading your paper, and it's a really interesting piece of work - well done!
On another note, thank you for including a citation to our work in your LinCIR paper; it's really appreciated!

While examining your code, I noticed some notable similarities. For example, the file 'validate.py' is almost identical. Could I kindly request that you include a citation to our code in your README?

On a friendly note, I noticed that the license information in the files borrowed from SEARLE is still intact. To be consistent with open-source practices, would you mind removing the license information from the files taken directly from our repository?

Thank you very much for your understanding and cooperation.

Best,
Alberto

**Comment by geonm** [comment]
Thank you for your interest in our paper and opening this issue.

When we release our code to the public, we typically use the Apache 2 license.

However, this time, we used a CC series license to align with SEARLE. Please forgive any imperfections related to the licensing in the open-source process.

Through this [PR](https://github.com/navervision/lincir/pull/2), I've removed any potential license notices that could be problematic within the code.

Additionally, I've added an acknowledgment in the README to express our special gratitude.

If you have any further suggestions or comments, could you please leave them?

**Comment by ABaldrati** [comment]
Hi @geonm 

Thanks for your swift response and addressing my concerns. I appreciate the quick resolution of the licensing issues and the addition of an acknowledgment in the README.

I've reviewed the changes in the pull request, and everything looks good. However, it seems there might be a typo in the link to SEARLE. Please double-check that to ensure it directs to the correct repository.

Best,
Alberto

**Comment by geonm** [comment]
@ABaldrati We fixed the typo thr this hot fix https://github.com/navervision/lincir/commit/4adff866af601fe269dfc46d45f57772f58dcb1e.

Thanks again. 😄
