### ISSUE TITLE
Why training and validation use the same function? (encode_with_pseudo_tokens_HF)

### ISSUE THREAD

**Issue by mcx-mcx** [navervision/lincir#13]
In the Line 239 of train_phi.py and Line 162 of validate.py, i.e.,https://github.com/navervision/lincir/blob/6ffbdebb665878285afcb8f5263a1f8a44937ad4/train_phi.py#L239 and https://github.com/navervision/lincir/blob/6ffbdebb665878285afcb8f5263a1f8a44937ad4/validate.py#L162, Why these two use the same function? The former's replaced_tokens contain not only one $, but the latter's tokenized_input_captions contain only one $. The meaning of the two usages is different, and the former assigns the same value to each $, which seems problematic.

**Comment by SanghyukChun** [comment]
Please check the previous comments. This is not a bug. Please check our paper as well
https://github.com/navervision/lincir/issues/12#issuecomment-1978102388
