### ISSUE TITLE
About ViT-G backbone pretrained  model

### ISSUE THREAD

**Issue by lan-lw** [navervision/lincir#15]
Hi, I tried to pretrained a phi model with ViT-G backbone, but the results are not as good. Can you provide a pretrained model with ViT-G as backbone?

**Comment by geonm** [comment]
Try reducing the validation steps to 50 or 100 and retrain the model.

Based on experience, in the case of Giga, we need to consider various methods to avoid overfitting.

However, proposing such methods is beyond the scope of this study, so we used the same training parameters for all training.

Using Giga as the backbone and training a phi model with LinCIR can lead to very quick convergence.

**Comment by lan-lw** [comment]
> Try reducing the validation steps to 50 or 100 and retrain the model.
> 
> Based on experience, in the case of Giga, we need to consider various methods to avoid overfitting.
> 
> However, proposing such methods is beyond the scope of this study, so we used the same training parameters for all training.
> 
> Using Giga as the backbone and training a phi model with LinCIR can lead to very quick convergence.

Got it, thanks!
