### ISSUE TITLE
About RTD method

### ISSUE THREAD

**Issue by MacG7ffin** [navervision/lincir#17]
I'd like to try the RTD method
Can you update the related codes about how to process the text captions in detail please?

**Comment by SanghyukChun** [comment]
Hi, thanks for your interest.
This repository is irrelevant to RTD (although some overlapping authors, including me, exist).
For RTD, we are preparing to release the code, but I am not sure when we will be available to release it.
I personally aim to release the code within August, but it is yet uncertain.
