### ISSUE TITLE
ImportError: cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by Penglianfeng** [navervision/lincir#22]
When I try to python demo.py,I can't run it normally.But
I have already install the huggingface_hub and updated to the latest version.Is it because 'cached_download'isn't in lastest version of library?

**Comment by geonm** [comment]
Since v0.26.0 huggingface_hub, `cached_download` has been deprecated.

See https://github.com/huggingface/huggingface_hub/releases/tag/v0.26.0

You can use `hf_hub_download` now.
