### ISSUE TITLE
Inquiry Regarding CLIP Pretrained Weights

### ISSUE THREAD

**Issue by yyc6631** [navervision/lincir#24]
when I attempt to replace openai/clip-vit-large-patch14 with laion/CLIP-ViT-L-14-laion2B-s32B-b82K, an error occurs.Could you please tell me how to properly load the pretrained weights for this model in LinCIR?

**Comment by geonm** [comment]
Hey, I sent an email but let's solve the problem here together.

Email I've sent is

> Thank you for your interest in our work.
> 
> I didn't try training LinCIR with the CLIP-Large model from the Laion group.
> 
> I think it should be okay to train LinCIR by putting the model name on the https://github.com/navervision/lincir/blob/master/models.py#L13
> 
> Can you share the error with me?

**Comment by yyc6631** [comment]
> Hey, I sent an email but let's solve the problem here together.
> 
> Email I've sent is
> 
> > Thank you for your interest in our work.
> > I didn't try training LinCIR with the CLIP-Large model from the Laion group.
> > I think it should be okay to train LinCIR by putting the model name on the https://github.com/navervision/lincir/blob/master/models.py#L13
> > Can you share the error with me?

When I add 'large': 'laion/CLIP-ViT-L-14-laion2B-s32B-b82K' to the clip_model_dict{} and run the training code for the phi model, I encounter the following error:
[rank0]: RuntimeError: Error(s) in loading state_dict for CLIPVisionModelWithProjection:
[rank0]:        size mismatch for visual_projection.weight: copying a param with shape torch.Size([768, 1024]) from checkpoint, the shape in current model is torch.Size([512, 1024]).
[rank0]:        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

**Comment by geonm** [comment]
Thanks.

It's a simple issus.

When folks from LAION pushed CLIP variations to Huggingface hub, they missed to set `"projection_dim"` in `config.json`. So, The model loader raised the `size mismatch` error because a default value for it is 512.

Specifically, I solved this issue for CLIP Giga model with [this PR](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/discussions/8).

You can refer the PR to handle the issue.

**Comment by yyc6631** [comment]
> Thanks.
> 
> It's a simple issus.
> 
> When folks from LAION pushed CLIP variations to Huggingface hub, they missed to set in . So, The model loader raised the error because a default value for it is 512.`"projection_dim"``config.json``size mismatch`
> 
> Specifically, I solved this issue for CLIP Giga model with [this PR](https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/discussions/8).
> 
> You can refer the PR to handle the issue.

After the modifications, it is now running successfully. Thanks a lot!

**Comment by geonm** [comment]
Happy to hear that.

Let's close the issue.
