### ISSUE TITLE
Using other models as backbone

### ISSUE THREAD

**Issue by hmd78** [navervision/lincir#7]
Hi, thank you for your interesting work,

I wonder if I can use other models than CLIP ( like BLIP, BLIP-2, etc) as backbone.

How can it be done?
What modifications need to be done?

**Comment by geonm** [comment]
Thank you for your interest.

Yes, LinCIR can be applied to other models like CoCa, BLIP, BLIP-2, and more.

As illustrated in Table B.1 in the appendix, BLIP ViT-B/16 demonstrates promising results when used with LinCIR.

Applying different backbones is straightforward.

You will need to define a textual feature extractor and a visual feature extractor for the new backbone, and designate a special token as described in Figure 3, represented by "$".

Note that in the CLIP tokenizer, "$" is tokenized as 259, but this may vary with other backbone models. Refer to [this line of code](https://github.com/navervision/lincir/blob/master/encode_with_pseudo_tokens.py#L32) for more details.

To employ the modality gap between visual and textual feature spaces, remember to freeze all backbone parameters and train only the phi model.

**Comment by hmd78** [comment]
Thank you for your precise answer.

My other question is, Can textual encoder and visual encoder be separate and not pretrained in a contrastive multi-modal manner?
I mean Can Phi model solely mitigate the modality gap of non-multi-modal encoders?
